name: Rust

on: 
   push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: apk add cargo && cargo build --release --verbose
    - name: Upload a build artifact
      uses: actions/upload-artifact@v2
      with:
        name: pcap2socks-latest-${{ runner.os }}-amd64
        path: ./target/release/pcap2socks
